# Generated by Django 3.2.5 on 2021-08-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210729_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_img_src',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_msg',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
